### ISSUE TITLE
Project files wont reopen if saved after TUFLOW Viewer is used

### ISSUE THREAD

**Issue by calumpeden** [TUFLOW-Support/QGIS-TUFLOW-Plugin#14]
I have come up against an issue where by if I save a QGIS project after TUFLOW viewer has been used to load xmdf results, and then close it it is not possible to reopen it. I am using QGIS 3.6.0. 
It doesnt come up with any error in QGIS when I try and open the project, it just hangs indefinitely.
It doesnt seem to matter if the project is saved as a .qgz or a .qgs file.

**Comment by TUFLOW-Support** [comment]
Hi, thanks for reporting this. This has hopefully been fixed now. I'll close the issue but if you find it still happens I am happy to re-open the issue (please let me know if it does).

Thanks
