### ISSUE TITLE
When saving "Cross Section / Long Profile" as PNG the saved image is the "Time Series"

### ISSUE THREAD

**Issue by ZedeN1** [TUFLOW-Support/QGIS-TUFLOW-Plugin#17]
If you try to _Export - Save_ from "Cross Section / Long Profile" it creates the image that contains the contents of your "Time Series" tab.

_Copy - Copy Image to Clipboard_ works OK.
_Export - Export Plot as CSV_ works OK.

> This is a release version of the TUFLOW QGIS utility
> Build: 3.0.4.2

> QGIS version | 3.8.3-Zanzibar | QGIS code branch | Release 3.8
> -- | -- | -- | --
> Compiled against Qt | 5.12.4 | Running against Qt | 5.12.4
> Compiled against GDAL/OGR | 2.4.2 | Running against GDAL/OGR | 2.4.2
> Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
> PostgreSQL Client Version | 11.5 (Ubuntu 11.5-1) | SpatiaLite Version | 4.3.0a
> QWT Version | 6.1.4 | QScintilla2 Version | 2.10.4
> Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
> OS Version | Ubuntu 19.10 |   |  

also tested on:

> This is a release version of the TUFLOW QGIS utility
> Build: 3.0.3

> QGIS version | 3.8.1-Zanzibar | QGIS code revision | dcd95cc648
> -- | -- | -- | --
> OS Version | Windows 10 (10.0)

**Comment by TUFLOW-Support** [comment]
Hi, it works for me and I can't seem to replicate the issue. What about other options under the export menu i.e. "Copy data to clipboard" or "Copy image to clipboard"?

**Comment by ZedeN1** [comment]
> Hi, it works for me and I can't seem to replicate the issue. What about other options under the export menu i.e. "Copy data to clipboard" or "Copy image to clipboard"?

> Copy - Copy Image to Clipboard works OK.
> Export - Export Plot as CSV works OK.

**Comment by TUFLOW-Support** [comment]
Hi thanks for the follow up information. I think I fixed the issue - can you please confirm that the issue was occurring through the **right click context menu -> export > save**.. and not through the **menu bar -> export > save**

Can you also please give the updated code a try?

Thanks

**Comment by ZedeN1** [comment]
New version fixed the issue, thanks!
Can confirm **working** with **both** context menu and menu bar. 

Sorry I did not know you could save the image via menu bar, this bug report was **only** about the right click context menu. I tried the menu bar save as png and it worked even on v3.0.4.2.
