### ISSUE TITLE
Fix for currentLayer.type()

### ISSUE THREAD

**Issue by ZedeN1** [TUFLOW-Support/QGIS-TUFLOW-Plugin#18]
For **some** of our Linux machines in the office, TUFLOW plugin doesn't work for time series results. The GIS layers are added, the plugin knows about the times, but it doesn't let you select the Result Type → Time Series → Level or Flow or any other (they are greyed out).

I am unable to find the correlation between QGIS version/ plugin version and this bug. Bug only happens on Linux Mint though... Kubuntu and Ubuntu Mate are OK.

### The following fixes the issues:

On line **118** in:
_QGIS-TUFLOW-Plugin/tuflow/tuflowqgis_tuviewer/tuflowqgis_tuview.py_

Instead of:
`if self.currentLayer.type() == 0:  # vector layer`
it should be 
`if self.currentLayer.type() == QgsMapLayerType.VectorLayer:  # vector layer`

**Comment by TUFLOW-Support** [comment]
Hi, thanks for finding this. I thought I had replaced all instances where an integer had been used instead of an explicit enumerator - obviously not since I scanned the code and found a few more. Hopefully I've now caught all of them.
