### ISSUE TITLE
Error where square brackets are used

### ISSUE THREAD

**Issue by anthony-cooper** [TUFLOW-Support/QGIS-TUFLOW-Plugin#21]
Where square brackets are used in the file/tlf name (eg Model_[EVENT]_[SCENARIO]_001 ) results viewer fails to pick up the the results in the tpc

**Comment by TUFLOW-Support** [comment]
Hi, thank you for letting us know and for looking into the issue. I think it used to be done via standard split however was changed to a regex split (I image in response to a previous issue). So instead I have used re.escape() to escape special characters. I have also searched through the rest of the code to do the same thing where required. Thanks again.
