### ISSUE TITLE
[Request] Add Value tool like features to TUFLOW Viewer plugin

### ISSUE THREAD

**Issue by ZedeN1** [TUFLOW-Support/QGIS-TUFLOW-Plugin#27]
It would be great if TUFLOW viewer would display the currently selected dataset value on mouse over. I am aware that it's possible to use _Live Tracking_ on a Temporal result to similar effect, but it can be extremely slow on large result files, and it doesn't work on maximums / bed elevation.

Feature is similar to [Value Tool plugin](https://github.com/jorgealmerio/valuetool):
![image](https://user-images.githubusercontent.com/18440960/101503084-68160900-397a-11eb-8d7a-e5a6285f9503.png)

But value tool only displays the Bed Elevation (.2dm) data it seems.

Possibly add another tab next to Vertical Profile called _Table_ and display all the currently selected/shown dataset results?

**Comment by TUFLOW-Support** [comment]
Hi, thanks for the suggestion. This is something that has been requested a few times now so is probably going to be bumped close to the top of the list of things to do. Adding it as an additional tab is a great idea. 

At the moment we're just trying to keep up with all the API changes occurring in QGIS as the temporal controller gets sorted. But we will definitely look to add new features like this soon!

**Comment by ZedeN1** [comment]
Well value tool developer added the feature in [v3.0.8](https://github.com/jorgealmerio/valuetool/issues/3#issuecomment-748709579) so not a pressing issue for myself anymore.

**Comment by TUFLOW-Support** [comment]
Thanks for letting me know. Rather than duplicating efforts, I might park this feature and close this ticket. Please feel free to reopen if things change (e.g. the value tool becomes deprecated).

Thanks
